version: '3'

services:
  stat_app:
    image: devexpress/support:stat_app
    restart: always
    hostname: stat_app
    container_name: stat_app
    command: nginx -g "daemon off;"

networks:
  default:
    name: support_analytics
    external: true
