import { SetState } from './Interfaces'
import { getSelector as getSlctr } from '../../../common/store/multiset_container/Selectors'
import { nameOf } from '../../../common/store/multiset_container/sets/Interfaces'

export const customersGroupsSelectorName = nameOf<SetState>('customersGroups')
export const ticketsTypesSelectorName = nameOf<SetState>('ticketsTypes')
export const platformsSelectorName = nameOf<SetState>('platforms')
export const productsSelectorName = nameOf<SetState>('products')
export const versionsSelectorName = nameOf<SetState>('versions')
export const ticketsTagsSelectorName = nameOf<SetState>('ticketsTags')
export const duplicatedToTicketsTypesSelectorName = nameOf<SetState>('duplicatedToTicketsTypes')
export const fixedInSelectorName = nameOf<SetState>('fixedIn')
export const fixedBySelectorName = nameOf<SetState>('fixedBy')
export const severitySelectorName = nameOf<SetState>('severity')
export const ticketStatusesSelectorName = nameOf<SetState>('ticketStatuses')
export const closedBySelectorName = nameOf<SetState>('closedBy')
export const frameworksSelectorName = nameOf<SetState>('frameworks')
export const operatingSystemsSelectorName = nameOf<SetState>('operatingSystems')
export const idesSelectorName = nameOf<SetState>('ides')
export const customersTypesSelectorName = nameOf<SetState>('customersTypes')
export const conversionsTypesSelectorName = nameOf<SetState>('conversionsTypes')
export const assignedToSelectorName = nameOf<SetState>('assignedTo')
export const repliesTypesSelectorName = nameOf<SetState>('repliesTypes')
export const componentsSelectorName = nameOf<SetState>('components')
export const featuresSelectorName = nameOf<SetState>('features')


function getSelector<R>(selector: (set: SetState | undefined) => R | undefined) {
    return getSlctr<SetState>(selector)
}

export const percentileSelector = getSelector(set => set?.percentile)
export const privacySelector = getSelector(set => set?.privacy)
export const ownerKindSelector = getSelector(set => set?.ownerKind)
export const closedForSelector = getSelector(set => set?.closedForInDays)
export const resolutionTimeSelector = getSelector(set => set?.resolutionTimeInhours)
export const customersGroupsSelector = getSelector(set => set?.customersGroups)
export const ticketsTypesSelector = getSelector(set => set?.ticketsTypes)
export const platformsSelector = getSelector(set => set?.platforms)
export const productsSelector = getSelector(set => set?.products)
export const versionsSelector = getSelector(set => set?.versions)
export const ticketsTagsSelector = getSelector(set => set?.ticketsTags)
export const duplicatedToTicketsTypesSelector = getSelector(set => set?.duplicatedToTicketsTypes)
export const fixedInSelector = getSelector(set => set?.fixedIn)
export const fixedBySelector = getSelector(set => set?.fixedBy)
export const fixedBetweenSelector = getSelector(set => set?.fixedBetween)
export const severitySelector = getSelector(set => set?.severity)
export const ticketStatusesSelector = getSelector(set => set?.ticketStatuses)
export const closedBySelector = getSelector(set => set?.closedBy)
export const closedBetweenSelector = getSelector(set => set?.closedBetween)
export const frameworksSelector = getSelector(set => set?.frameworks)
export const operatingSystemsSelector = getSelector(set => set?.operatingSystems)
export const idesSelector = getSelector(set => set?.ides)
export const customersTypesSelector = getSelector(set => set?.customersTypes)
export const conversionsTypesSelector = getSelector(set => set?.conversionsTypes)
export const assignedToSelector = getSelector(set => set?.assignedTo)
export const repliesTypesSelector = getSelector(set => set?.repliesTypes)
export const componentsSelector = getSelector(set => set?.components)
export const featuresSelector = getSelector(set => set?.features)
export const customersSelector = getSelector(set => set?.customers)
