export const ENGINEERING_METRICS = '/EngineeringMetrics'
export const FORECASTER = '/forecaster'
export const SUPPORT_METRICS = '/CustomersActivity'
export const COST_METRICS = '/CostMetrics'
export const PERFORMANCE_METRICS = '/PerformanceMetrics'
